### ISSUE TITLE
JS can add/remove inputs that don't belong together.

### ISSUE THREAD

**Issue by csenger** [kitconcept/pas.plugins.memberpropertytogroup#36]
2 input belong together: "Users Group Property Field" and "Mapped Groups".
z3c.form adds and empty class to the field.div if the input is empty.

If somebody fills in "Users Group Property Field", but leaves the "Mapped Groups" empty and saves the form, it will be rended the next time like this: 

```
Users Group Property Field
[ foo bar                       ]

[Add Property] [Remove Property]
[Save] [Cancel]
```

The "Mapped Groups input is invisible cause it has the css class 'empty'.
If you click 'Add Property' JS shows the missing "Mapped Groups" and the next "Users Group Property Field":

```
Users Group Property Field
[ foo bar                       ]

Mapped Groups
[                               ]

Users Group Property Field
[                               ]


[Add Property] [Remove Property]
[Save] [Cancel]
```

If a "Mapped Groups" in between is empty it is hidden by default and will be shown on 'Add Property'.

If a  "Users Group Property Field" is empty it is hidden by default and will be shown on 'Add Property'

**Comment by sneridagh** [comment]
Refactored in pull request #38 to fix this behavior. Added aditional markup to gain better control of the coupled fields.
