### ISSUE TITLE
Scenario: As administrator I can create a group based on member properties prefixes

### ISSUE THREAD

**Issue by tisto** [kitconcept/pas.plugins.memberpropertytogroup#4]
_From @tisto on June 12, 2015 9:29_

  Given a user 'John Doe' with the property 'student_id' = '1234567'
    and a logged-in manager
   When I create a virtual group 'Students' based on the property 'student' = '123*'
   Then the user 'John Doe' is member of the group 'Students'

https://github.com/kitconcept/collective.memberpropertytogroup/blob/master/src/collective/memberpropertytogroup/tests/robot/test_acceptance.robot

_Copied from original issue: kitconcept/collective.memberpropertytogroup#4_

**Comment by jensens** [comment]
see #17

**Comment by jensens** [comment]
scenario is now passing.
