### ISSUE TITLE
Scenario: As administrator I can create a group based on multiple member properties

### ISSUE THREAD

**Issue by tisto** [kitconcept/pas.plugins.memberpropertytogroup#5]
_From @tisto on June 12, 2015 9:29_

  Given a user 'John Doe' with the property 'usertype' = 'employee'
    and a virtual group 'Employees' based on the member property 'usertype' with the value 'employee'
    and a logged-in reviewer
   When I grant the user 'John Doe' the 'edit' permission on a folder
   Then the user 'John Doe' can edit the folder

https://github.com/kitconcept/collective.memberpropertytogroup/blob/master/src/collective/memberpropertytogroup/tests/robot/test_acceptance.robot

_Copied from original issue: kitconcept/collective.memberpropertytogroup#3_

**Comment by jensens** [comment]
Task addresses the Robot-Test I suppose?
