### ISSUE TITLE
Scenario: As reviewer I can grant permissions based on member properties groups

### ISSUE THREAD

**Issue by tisto** [kitconcept/pas.plugins.memberpropertytogroup#6]
_From @tisto on June 12, 2015 9:28_

  Given a user 'John Doe' with the property 'usertype' = 'employee'
    and a user 'Jane Doe' with the property 'city' = 'bonn'
    and a logged-in manager
   When I create a virtual group 'Employees' based on the property 'usertype' = 'employee'
    and I create a virtual group 'Locals' based on the property 'city' = 'bonn'
   Then the user 'John Doe' is member of the group 'Employees'
    and the user 'Jane Doe' is member of the group 'Locals'

https://github.com/kitconcept/collective.memberpropertytogroup/blob/master/src/collective/memberpropertytogroup/tests/robot/test_acceptance.robot

_Copied from original issue: kitconcept/collective.memberpropertytogroup#2_

**Comment by jensens** [comment]
Task addresses the Robot-Test I suppose?
