### ISSUE TITLE
Scenario: As administrator I can create a group based on member properties

### ISSUE THREAD

**Issue by tisto** [kitconcept/pas.plugins.memberpropertytogroup#7]
_From @tisto on June 12, 2015 9:28_

  Given a user 'John Doe' with the property 'usertype' = 'employee'
    and a logged-in manager
   When I create a virtual group 'Employees' based on the property 'usertype' = 'employee'
   Then the user 'John Doe' is member of the group 'Employees'

https://github.com/kitconcept/collective.memberpropertytogroup/blob/master/src/collective/memberpropertytogroup/tests/robot/test_acceptance.robot

_Copied from original issue: kitconcept/collective.memberpropertytogroup#1_

**Comment by jensens** [comment]
Task addresses the Robot-Test I suppose?

**Comment by tisto** [comment]
Yes. Actually both test and functionality. If the functionality is in place I'm happy to write the robot tests for it. Is there anything special that we need for the test fixture?

**Comment by jensens** [comment]
While running this I got this error:

    Running pas.plugins.memberpropertytogroup.testing.PasPluginsMPTGPloneLayer:AcceptanceTesting tests:
      Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
      Set up plone.testing.z2.Startup in 0.185 seconds.
      Set up plone.app.testing.layers.PloneFixture in 10.257 seconds.
      Set up pas.plugins.memberpropertytogroup.testing.PasPluginsMPTGPloneLayer in 1.746 seconds.
      Set up plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.006 seconds.
      Set up plone.testing.z2.ZServer in 0.503 seconds.
      Set up pas.plugins.memberpropertytogroup.testing.PasPluginsMPTGPloneLayer:AcceptanceTesting in 0.000 seconds.
      Running:
        1/4 (25.0%)

    Error in test Scenario As administrator I can create a group based on member properties (test_acceptance.robot)
    Traceback (most recent call last):
      File "/home/jensens/.buildout/shared-eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
        testMethod()
      File "/home/jensens/.buildout/shared-eggs/robotsuite-1.6.1-py2.7.egg/robotsuite/__init__.py", line 393, in runTest
        shutil.copyfile(path, "%s%s" % (prefix, copy_filename))
      File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 36] File name too long: u'robot_test_acceptance_Scenario_As_administrator_I_can_create_a_group_based_on_member_properties_docssource_screenshotsmemberpropertytogroup-controlpanel.png'

**Comment by tisto** [comment]
@jensens ok, will look into it. strange that this does not occur on travis. How do you run the tests? "bin/test --all"?

**Comment by jensens** [comment]
exact like this. and its on a standard ext4 volume.

**Comment by jensens** [comment]
so, I got it: my home is encrypted, so ecryptfs is layered on top of ext4. filenames got encrypted too, so they need more space on ext4, this roughly results in ~140bytes expanding to ~255 bytes - which is the max length on ext4 (and most other unix filesystems).
